server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.php index.html;

    client_max_body_size 16m;

    # 原项目 /api/* -> Clover-Lite/index.php
    location /api/ {
        rewrite ^/api/.*$ /Clover-Lite/index.php last;
    }

    # cache 不进入 Clover-Lite 路由
    location /Clover-Lite/cache/ {
        try_files $uri =404;
    }

    # Clover-Lite 非真实文件交给框架入口
    location /Clover-Lite/ {
        try_files $uri $uri/ /Clover-Lite/index.php?$query_string;
    }

    # 普通静态文件/目录
    location / {
        try_files $uri $uri/ =404;
    }

    # PHP
    location ~ \.php$ {
        try_files $uri =404;

        include fastcgi_params;

        fastcgi_pass php:9000;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;

        #
        # VioletBlue 很多 PHP 页面会执行：
        #
        # file_get_contents(
        #   'http://' . $_SERVER['HTTP_HOST'] . '/api/siteInfo'
        # )
        #
        # 因为 PHP-FPM 和 Nginx 是两个容器，
        # 这里把 HTTP_HOST 设置成 Docker 服务名 nginx。
        #
        # 因此 PHP 内部会请求：
        #
        # http://nginx/api/siteInfo
        #
        fastcgi_param HTTP_HOST nginx;
    }

    # 禁止访问隐藏文件
    location ~ /\.(?!well-known).* {
        deny all;
    }
}